package com.test.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IMyServer", targetNamespace = "http://webservice.test.com/")
public interface IMyServer {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getMyName", targetNamespace = "http://webservice.test.com/", className = "com.test.ws.GetMyName")
	@ResponseWrapper(localName = "getMyNameResponse", targetNamespace = "http://webservice.test.com/", className = "com.test.ws.GetMyNameResponse")
	public String getMyName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
