package com.test.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MyServerImplService service = new MyServerImplService();
 * IMyServer portType = service.getMyServerImplPort();
 * portType.getMyName(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MyServerImplService", targetNamespace = "http://impl.webservice.test.com/", wsdlLocation = "http://192.168.10.152:9999/myws?wsdl")
public class MyServerImplService extends Service {

	private final static URL MYSERVERIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.test.ws.MyServerImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.test.ws.MyServerImplService.class.getResource(".");
			url = new URL(baseUrl, "http://192.168.10.152:9999/myws?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://192.168.10.152:9999/myws?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MYSERVERIMPLSERVICE_WSDL_LOCATION = url;
	}

	public MyServerImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MyServerImplService() {
		super(MYSERVERIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://impl.webservice.test.com/", "MyServerImplService"));
	}

	/**
	 * 
	 * @return returns IMyServer
	 */
	@WebEndpoint(name = "MyServerImplPort")
	public IMyServer getMyServerImplPort() {
		return super.getPort(new QName("http://impl.webservice.test.com/",
				"MyServerImplPort"), IMyServer.class);
	}

}
